version: '3.3'

networks:
  net:
    driver: overlay
    attachable: true
  traefik-public:
    external: true

volumes:
  olw-assets:

services:
  assets:
    image: mullenkamp/olw-monitoring-app-assets:1.22
    volumes:
      - olw-assets:/app/assets
    networks:
      - net
      # - traefik-public
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.labels.function == web_server

  dash:
    image: mullenkamp/olw-monitoring-app:3.9
    volumes:
      - olw-assets:/app/assets
    networks:
      # - net
      - traefik-public
    depends_on:
      - assets
    deploy:
      replicas: 10
      placement:
        constraints:
          - node.labels.function == web_server
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.olw-app-base-http.rule=Host(`olw-app.nzrivers.xyz`)
        - traefik.http.routers.olw-app-base-http.entrypoints=http
        - traefik.http.routers.olw-app-base-http.middlewares=https-redirect
        - traefik.http.routers.olw-app-base-https.rule=Host(`olw-app.nzrivers.xyz`)
        - traefik.http.routers.olw-app-base-https.entrypoints=https
        - traefik.http.routers.olw-app-base-https.tls=true
        # - traefik.http.routers.es-dash-https.tls.certresolver=le
        - traefik.http.services.olw-app-base.loadbalancer.server.port=80
