version: '3.3'

networks:
  # net:
  #   driver: overlay
  #   attachable: true
  traefik-public:
    external: true

services:
  dash:
    image: tethysts/olw-monitoring-app:1.3
    networks:
      # - net
      - traefik-public
    deploy:
      placement:
        constraints:
          - node.labels.function == web_server
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.olw-vis-http.rule=Host(`olw-vis.nzrivers.xyz`)
        - traefik.http.routers.olw-vis-http.entrypoints=http
        - traefik.http.routers.olw-vis-http.middlewares=https-redirect
        - traefik.http.routers.olw-vis-https.rule=Host(`olw-vis.nzrivers.xyz`)
        - traefik.http.routers.olw-vis-https.entrypoints=https
        - traefik.http.routers.olw-vis-https.tls=true
        # - traefik.http.routers.es-dash-https.tls.certresolver=le
        - traefik.http.services.olw-vis.loadbalancer.server.port=80
